language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

before_install:
    - composer self-update
    - rm composer.lock

install:
    - composer install --no-interaction --prefer-source

script:
    - bash bin/tests.sh ci

allow_failures:
    -   php: 7.4snapshot
    -   php: nightly

after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
