services:
    db:
        build: .docker/mariadb
        restart: no
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: sandbox
            MYSQL_USER: root
            MYSQL_PASSWORD: heslo

    www:
        build: .docker/php
        depends_on:
            - db
        restart: no
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
