version: "3.3"

networks:
    docker_network:
        driver: bridge

services:
    db:
        container_name: sandbox_db
        image: mysql:5.7
        restart: always
        networks:
            - docker_network
        ports:
            - 3306:3306
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: heslo
            MYSQL_DATABASE: sandbox
            MYSQL_USER: root
            MYSQL_PASSWORD: heslo

    www:
        container_name: sandbox_www
        build: .docker
        depends_on:
            - db
        restart: always
        networks:
            - docker_network
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./.docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.docker/php.ini:/usr/local/etc/php/php.ini
